-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.departments (
  id integer NOT NULL DEFAULT nextval('departments_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  first_name text NOT NULL,
  surname text NOT NULL,
  email text NOT NULL UNIQUE,
  department text NOT NULL DEFAULT 'osh'::text CHECK (department = ANY (ARRAY['osh'::text, 'company'::text, 'general'::text, 'medical'::text])),
  location text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role text DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['viewer'::text, 'officer'::text, 'admin'::text, 'super_admin'::text, 'company'::text, 'worker'::text, 'medical_practitioner'::text])),
  company_id uuid,
  designation text,
  last_sign_in timestamp with time zone,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fk_user_profiles_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.login_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  login_time timestamp with time zone DEFAULT now(),
  logout_time timestamp with time zone,
  ip_address inet,
  user_agent text,
  login_successful boolean DEFAULT true,
  session_duration interval,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT login_history_pkey PRIMARY KEY (id),
  CONSTRAINT login_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.password_reset_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  ip_address inet,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'expired'::text, 'cancelled'::text])),
  CONSTRAINT password_reset_requests_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  activity_type text NOT NULL,
  activity_description text,
  metadata jsonb,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT user_activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.injury_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_number text UNIQUE,
  name_of_employer text NOT NULL,
  industry text NOT NULL,
  name_of_claimant text NOT NULL,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['M'::text, 'F'::text])),
  location text NOT NULL,
  nationality text NOT NULL,
  date_of_injury date NOT NULL,
  date_reported date NOT NULL,
  date_received date NOT NULL,
  cause text NOT NULL,
  nature text NOT NULL,
  incapacity_percentage numeric NOT NULL CHECK (incapacity_percentage >= 0::numeric AND incapacity_percentage <= 100::numeric),
  submitted_by uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'closed'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  claimant_id_number text,
  worker_registry_id uuid,
  source_type text CHECK (source_type IS NULL OR (source_type = ANY (ARRAY['accident'::text, 'injury_disease'::text, 'manual'::text]))),
  source_id uuid,
  CONSTRAINT injury_claims_pkey PRIMARY KEY (id),
  CONSTRAINT injury_claims_worker_registry_id_fkey FOREIGN KEY (worker_registry_id) REFERENCES public.workers_registry(id),
  CONSTRAINT injury_claims_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles_info (
  role text NOT NULL,
  display_name text NOT NULL,
  description text NOT NULL,
  permissions jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_info_pkey PRIMARY KEY (role)
);
CREATE TABLE public.role_change_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  old_role text,
  new_role text,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  reason text,
  CONSTRAINT role_change_log_pkey PRIMARY KEY (id),
  CONSTRAINT role_change_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT role_change_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.workplace_inspections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_number text NOT NULL,
  inspection_date date NOT NULL,
  date_report_sent date,
  days_to_respond integer,
  factory_name text NOT NULL,
  location text NOT NULL,
  nature_of_work text NOT NULL,
  industry_type text NOT NULL CHECK (industry_type = ANY (ARRAY['Manufacturing'::text, 'Services'::text, 'Construction'::text, 'Agriculture'::text, 'Transport'::text, 'Retail'::text, 'Government'::text, 'Parastatal'::text])),
  registration_status text NOT NULL CHECK (registration_status = ANY (ARRAY['Yes'::text, 'No'::text, 'N/A'::text])),
  inspection_type text NOT NULL CHECK (inspection_type = ANY (ARRAY['Routine'::text, 'Follow-up'::text, 'Query'::text, 'First Time'::text])),
  employees_male integer NOT NULL DEFAULT 0 CHECK (employees_male >= 0),
  employees_female integer NOT NULL DEFAULT 0 CHECK (employees_female >= 0),
  inspector_name text NOT NULL,
  s9 boolean DEFAULT false,
  s13 boolean DEFAULT false,
  s14 boolean DEFAULT false,
  s15 boolean DEFAULT false,
  s16 boolean DEFAULT false,
  s18 boolean DEFAULT false,
  s41 boolean DEFAULT false,
  s42 boolean DEFAULT false,
  s46 boolean DEFAULT false,
  s47 boolean DEFAULT false,
  s48 boolean DEFAULT false,
  s49 boolean DEFAULT false,
  s52 boolean DEFAULT false,
  s53 boolean DEFAULT false,
  s62 boolean DEFAULT false,
  s66 boolean DEFAULT false,
  s67 boolean DEFAULT false,
  s17 boolean DEFAULT false,
  s23 boolean DEFAULT false,
  s29 boolean DEFAULT false,
  s30 boolean DEFAULT false,
  s31 boolean DEFAULT false,
  s32 boolean DEFAULT false,
  s34 boolean DEFAULT false,
  s37 boolean DEFAULT false,
  s38 boolean DEFAULT false,
  s39 boolean DEFAULT false,
  s51 boolean DEFAULT false,
  s54 boolean DEFAULT false,
  s57 boolean DEFAULT false,
  s58 boolean DEFAULT false,
  total_contraventions integer NOT NULL DEFAULT 0,
  non_compliance_pct integer NOT NULL DEFAULT 0 CHECK (non_compliance_pct >= 0 AND non_compliance_pct <= 100),
  compliance_level integer NOT NULL DEFAULT 100 CHECK (compliance_level >= 0 AND compliance_level <= 100),
  contraventions ARRAY,
  plant_machinery jsonb,
  action_taken text NOT NULL CHECK (action_taken = ANY (ARRAY['Advised to Comply'::text, 'Warned'::text, 'Compliance Satisfactory'::text, 'Prohibition Notice Issued'::text, 'Improvement Notice Issued'::text, 'Prosecution Recommended'::text])),
  follow_up_required boolean NOT NULL DEFAULT false,
  follow_up_date date,
  summary_findings text,
  non_compliances text,
  recommendations text,
  submitted_by uuid,
  status text NOT NULL DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['draft'::text, 'completed'::text, 'reviewed'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  employees_foreign_male integer NOT NULL DEFAULT 0,
  employees_foreign_female integer NOT NULL DEFAULT 0,
  CONSTRAINT workplace_inspections_pkey PRIMARY KEY (id),
  CONSTRAINT workplace_inspections_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.accident_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['accident'::text, 'dangerous_occurrence'::text, 'both'::text])),
  occupier_name text NOT NULL,
  premises_address text NOT NULL,
  nature_of_industry text NOT NULL,
  industry_sector text NOT NULL CHECK (industry_sector = ANY (ARRAY['Manufacturing'::text, 'Services'::text, 'Construction'::text, 'Agriculture'::text, 'Transport'::text, 'Retail'::text, 'Government'::text, 'Parastatal'::text])),
  injured_name text,
  injured_age integer CHECK (injured_age > 0 AND injured_age < 120),
  injured_sex text CHECK (injured_sex = ANY (ARRAY['Male'::text, 'Female'::text])),
  injured_id_number text,
  occupation_at_accident text,
  usual_occupation text,
  experience_level text,
  accident_date date,
  accident_time time without time zone,
  accident_place text,
  accident_description text,
  machinery_involved text,
  injury_fatal text CHECK (injury_fatal = ANY (ARRAY['Fatal'::text, 'Non-fatal'::text])),
  disabled_three_days text CHECK (disabled_three_days = ANY (ARRAY['Yes'::text, 'No'::text])),
  hourly_pay numeric,
  medical_practitioner text,
  dangerous_date date,
  dangerous_time time without time zone,
  dangerous_place text,
  dangerous_description text,
  dangerous_damage text,
  employees_injured text CHECK (employees_injured = ANY (ARRAY['Yes'::text, 'No'::text])),
  notification_submitted text CHECK (notification_submitted = ANY (ARRAY['Yes'::text, 'No'::text])),
  outside_persons_injured text,
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  reporter_name text NOT NULL,
  reporter_designation text,
  causation_number text,
  date_received date,
  investigation_status text DEFAULT 'Pending'::text CHECK (investigation_status = ANY (ARRAY['Pending'::text, 'In Progress'::text, 'Completed'::text, 'Closed'::text])),
  official_action text,
  submitted_by uuid,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'investigated'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  worker_registry_id uuid,
  CONSTRAINT accident_reports_pkey PRIMARY KEY (id),
  CONSTRAINT accident_reports_worker_registry_id_fkey FOREIGN KEY (worker_registry_id) REFERENCES public.workers_registry(id),
  CONSTRAINT accident_reports_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.injury_disease_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_name text NOT NULL,
  worker_address text NOT NULL,
  occupation text NOT NULL,
  worker_id_number text,
  incident_date date NOT NULL,
  place_of_accident text NOT NULL,
  incident_type text NOT NULL CHECK (incident_type = ANY (ARRAY['Injury'::text, 'Disease'::text, 'Both'::text])),
  nature_of_injuries text NOT NULL,
  resulted_death text CHECK (resulted_death = ANY (ARRAY['Yes'::text, 'No'::text])),
  permanent_incapacity text CHECK (permanent_incapacity = ANY (ARRAY['Yes'::text, 'No'::text])),
  temporary_incapacity text CHECK (temporary_incapacity = ANY (ARRAY['Yes'::text, 'No'::text])),
  nok_informed text CHECK (nok_informed = ANY (ARRAY['Yes'::text, 'No'::text])),
  employer_name text NOT NULL,
  employer_telephone text,
  employer_fax text,
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  signatory_name text,
  signatory_designation text,
  submitted_by uuid,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'processed'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  worker_registry_id uuid,
  CONSTRAINT injury_disease_reports_pkey PRIMARY KEY (id),
  CONSTRAINT injury_disease_reports_worker_registry_id_fkey FOREIGN KEY (worker_registry_id) REFERENCES public.workers_registry(id),
  CONSTRAINT injury_disease_reports_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.workers_registry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_number text NOT NULL UNIQUE,
  id_type text NOT NULL DEFAULT 'Omang'::text CHECK (id_type = ANY (ARRAY['Omang'::text, 'Passport'::text])),
  full_name text NOT NULL,
  date_of_birth date,
  sex text CHECK (sex = ANY (ARRAY['Male'::text, 'Female'::text])),
  nationality text,
  address text,
  occupation text,
  employer_name text,
  employer_address text,
  employer_telephone text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  usual_occupation text,
  experience_level text,
  employer_fax text,
  age_years integer CHECK (age_years IS NULL OR age_years > 0 AND age_years < 120),
  CONSTRAINT workers_registry_pkey PRIMARY KEY (id),
  CONSTRAINT workers_registry_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT workers_registry_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL UNIQUE,
  industry text,
  location text,
  telephone text,
  owner_name text,
  owner_email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cipa_number text,
  physical_address text,
  plot_number text,
  street_name text,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inspection_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  company_id uuid,
  contact_name text NOT NULL,
  contact_email text NOT NULL,
  contact_phone text,
  preferred_date date,
  preferred_time text,
  inspection_type text NOT NULL DEFAULT 'Routine'::text CHECK (inspection_type = ANY (ARRAY['Routine'::text, 'Follow-up'::text, 'First Time'::text, 'Query'::text])),
  location text NOT NULL,
  nature_of_work text,
  industry_type text,
  notes text,
  special_requirements text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'scheduled'::text, 'completed'::text, 'cancelled'::text])),
  assigned_inspector text,
  scheduled_date date,
  scheduled_time text,
  admin_notes text,
  submitted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inspection_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_bookings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT inspection_bookings_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.medical_examination_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid,
  worker_registry_id uuid,
  worker_name text NOT NULL,
  worker_id_number text,
  claim_file_number text,
  nature_of_injury_or_disease text NOT NULL,
  medical_treatment_particulars text NOT NULL,
  death_incapacity boolean DEFAULT false,
  permanent_total_incapacity boolean DEFAULT false,
  permanent_partial_incapacity boolean DEFAULT false,
  temporary_incapacity boolean DEFAULT false,
  temporary_probable_duration text,
  incapacity_percentage numeric,
  capable_light_duties text CHECK (capable_light_duties = ANY (ARRAY['Yes'::text, 'No'::text, 'Not applicable'::text])),
  final_examination_necessary text CHECK (final_examination_necessary = ANY (ARRAY['Yes'::text, 'No'::text, 'Not applicable'::text])),
  able_to_resume_work text CHECK (able_to_resume_work = ANY (ARRAY['Yes'::text, 'No'::text, 'Not applicable'::text])),
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  practitioner_name text NOT NULL,
  practitioner_designation text NOT NULL,
  worker_representative_name text,
  submitted_by uuid,
  status text DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medical_examination_reports_pkey PRIMARY KEY (id),
  CONSTRAINT medical_examination_reports_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.injury_claims(id),
  CONSTRAINT medical_examination_reports_worker_registry_id_fkey FOREIGN KEY (worker_registry_id) REFERENCES public.workers_registry(id),
  CONSTRAINT medical_examination_reports_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.permanent_impairment_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid,
  worker_registry_id uuid,
  worker_name text NOT NULL,
  wcc_ref_no text,
  date_of_birth date,
  hospital_name_ref text,
  sex text CHECK (sex = ANY (ARRAY['Male'::text, 'Female'::text])),
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  medical_history jsonb DEFAULT '{}'::jsonb,
  physical_examination text,
  radiological_exam text,
  laboratory_test text,
  special_therapeutic_procedures text,
  specialists_evaluation text,
  pre_existing_conditions text,
  impairment_a text,
  impairment_b text,
  impairment_c text,
  impairment_d text,
  impairment_e text,
  condition_a_text text,
  condition_b_permanent text CHECK (condition_b_permanent = ANY (ARRAY['Yes'::text, 'No'::text])),
  condition_c_not_stabilized text CHECK (condition_c_not_stabilized = ANY (ARRAY['Yes'::text, 'No'::text])),
  unfit_pre_injury_occupation text CHECK (unfit_pre_injury_occupation = ANY (ARRAY['Yes'::text, 'No'::text])),
  unfit_reasons text,
  fit_alternative_duty text CHECK (fit_alternative_duty = ANY (ARRAY['Yes'::text, 'No'::text])),
  further_harm_possible text CHECK (further_harm_possible = ANY (ARRAY['Yes'::text, 'No'::text])),
  further_harm_explanation text,
  restrictions_needed text CHECK (restrictions_needed = ANY (ARRAY['Yes'::text, 'No'::text])),
  restrictions_explanation text,
  incapacity_body_parts jsonb DEFAULT '[]'::jsonb,
  total_incapacity_pct numeric,
  under_care_from date,
  under_care_to date,
  not_provided_care boolean DEFAULT false,
  seen_patient_times integer,
  practitioner_name text NOT NULL,
  practitioner_signature text,
  practitioner_date date,
  practitioner_address text,
  practitioner_tel text,
  practitioner_registered_bhpc text CHECK (practitioner_registered_bhpc = ANY (ARRAY['Yes'::text, 'No'::text])),
  practitioner_registered_as text,
  submitted_by uuid,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'under_review'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT permanent_impairment_reports_pkey PRIMARY KEY (id),
  CONSTRAINT permanent_impairment_reports_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.injury_claims(id),
  CONSTRAINT permanent_impairment_reports_worker_registry_id_fkey FOREIGN KEY (worker_registry_id) REFERENCES public.workers_registry(id),
  CONSTRAINT permanent_impairment_reports_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.practitioner_clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  practitioner_id uuid NOT NULL,
  worker_registry_id uuid,
  worker_name text NOT NULL,
  worker_id_number text,
  last_exam_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT practitioner_clients_pkey PRIMARY KEY (id),
  CONSTRAINT practitioner_clients_practitioner_id_fkey FOREIGN KEY (practitioner_id) REFERENCES auth.users(id),
  CONSTRAINT practitioner_clients_worker_registry_id_fkey FOREIGN KEY (worker_registry_id) REFERENCES public.workers_registry(id)
);